---
- name: Configure application
  hosts: all
  become: true
  tasks:
    - name: install docker
      package: 
        name: docker
        state: present
    - name: enable docker service
      service:
        name: docker
        status: started
        enabled: yes
    - name: run container
      shell: "docker run --name reddit -d -p 9292:9292 aleshkashell/otus-reddit:1.0"

